import type { BlogBlock } from "./blog";

// Cuerpo completo de cada nota, extraído del sitio real (elevar.com.ar/blog).
// Clave = slug de la nota. Texto verbatim del sitio.
export const BLOG_CONTENT: Record<string, BlogBlock[]> = {
  "componentes-incertidumbre-microbiologia-iso-19036": [
    { type: "p", text: `¿Conoces los 3 componentes de la incertidumbre en microbiología? Para conocer sobre ellos vamos a centrarnos en la norma ISO 19036 - Microbiología de la cadena alimentaria - Estimación de la incertidumbre de medida para determinaciones cuantitativas. En este documento, de referencia internacional, se proponen 2 opciones:` },
    { type: "li", text: `Informar un valor general de incertidumbre basado solo en una desviación estándar de reproducibilidad (SR), si es consistente con los protocolos de laboratorio y los requisitos del cliente.` },
    { type: "li", text: `Considerar tres tipos distintos de componentes de incertidumbre, las que pueden estimarse por separado y finalmente combinarlas.` },
    { type: "h", text: `Primer componente - Incertidumbre técnica` },
    { type: "p", text: `Surge de la variabilidad operativa y se estima, utilizando un enfoque global, a partir de la desviación estándar de reproducibilidad (SR) del resultado final del proceso de medición. Las formas de calcular el SR pueden ser:` },
    { type: "li", text: `SR intralaboratorio` },
    { type: "li", text: `SR interlaboratorio (validación - estudio colaborativo)` },
    { type: "li", text: `SR interlaboratorio (ensayo de aptitud)` },
    { type: "h", text: `Segundo componente - Incertidumbre matricial` },
    { type: "p", text: `Surge de una mezcla imperfecta de la muestra de laboratorio. Se refiere solo a los efectos de la distribución microbiana en una matriz dada, es decir, la variación entre los resultados de diferentes porciones de prueba tomadas de una misma muestra de laboratorio. Refleja la medida en que las porciones de pruebas individuales no son representativas de la muestra de laboratorio general.` },
    { type: "h", text: `Tercer componente - Incertidumbre distributiva` },
    { type: "p", text: `Incluso en matrices homogéneas, la distribución aleatoria de microorganismos conduce a este tipo de incertidumbre, de las cuales hay tres tipos potenciales para las técnicas de recuento de colonias:` },
    { type: "li", text: `Incertidumbre de Poisson: donde el valor se toma por tabla según el recuento total de colonias` },
    { type: "li", text: `Incertidumbre de confirmación: donde se aplica para corregir los recuentos presuntivos de organismos (número de colonias confirmadas respecto de las testeadas)` },
    { type: "li", text: `Incertidumbre de NMP: donde la variabilidad intrínseca de un valor de NMP es mayor que la asociada con la distribución de Poisson debido a un elemento adicional de probabilidad binomial asociado con la naturaleza positiva o negativa de los datos.` },
    { type: "p", text: `Con esta información y análisis, podemos ver que todo sistema de medición presenta errores de medida. La incertidumbre es el eslabón que acompaña al valor medido para generar una medición completa. Por esta razón es importante incluir la incertidumbre en métodos microbiológicos, ya que verás la diferencia en la calidad de tus resultados.` },
  ],
  "fuentes-de-deteccion-de-no-conformidades": [
    { type: "p", text: `¿En qué momento se detectan no conformidades en tu laboratorio? Es interesante plantearse de forma introspectiva esta pregunta ya que es necesario que dentro de la organización se comprenda la importancia de generar un compromiso con la detección de incumplimientos, pensándolos como oportunidades para crecer y no como un castigo o enojo inminente.` },
    { type: "p", text: `Te compartimos en esta nota diferentes situaciones donde podrás encontrar dentro del laboratorio no conformidades, para que estés atento y puedas identificar incumplimientos:` },
    { type: "h", text: `🔸 Quejas de clientes` },
    { type: "p", text: `las quejas de los clientes son el origen de no conformidades asociadas a diferentes situaciones dentro del laboratorio, como por ejemplo:` },
    { type: "li", text: `requisitos mal comunicados: no se detallan o se detallan incorrectamente en el presupuesto u orden de trabajo las condiciones de ensayo, fechas de entrega, método de ensayo a utilizar, forma de extracción de muestra, forma de envío de muestras, costos detallados incorrectamente, etc.` },
    { type: "li", text: `atención o interacción entre cliente - laboratorio inapropiada: generada por comunicaciones violentas, falta de respuesta a solicitudes, interpretaciones o comentarios sobre resultados incorrectos u subjetivos, etc.` },
    { type: "li", text: `errores en los informes emitidos: unidades incorrectas, resultados incorrectos o inconsistentes, datos de cliente descritos erróneamente, etc.` },
    { type: "li", text: `coordinación de actividades de muestreo incorrectas: información sobre coordenadas para la extracción de muestra incorrectas, fechas u horarios mal acordados, etc.` },
    { type: "h", text: `🔸 Controles de calidad del ensayo` },
    { type: "p", text: `En el aseguramiento de la calidad de los ensayos, suelen detectarse no conformidades, por ejemplo en:` },
    { type: "li", text: `el análisis de gráficos de control con datos fuera de límites o tendencias` },
    { type: "li", text: `los criterios de ensayos, por ejemplo para replicados que se incumplen` },
    { type: "li", text: `el análisis de tendencias en gráficos verificaciones intermedias de equipos, indicando que el mismo necesita atención` },
    { type: "li", text: `la evaluación de certificados de calibración de equipos con datos fuera de especificaciones` },
    { type: "li", text: `las pruebas de ensayos de aptitud, intralaboratorios o muestras ciegas con resultados insatisfactorios` },
    { type: "h", text: `🔸 Avisos del personal` },
    { type: "p", text: `Quizás sea la herramienta más potente, y a la vez la más compleja de hacer que fluya con naturalidad dentro del laboratorio. Podemos ver al personal detectando incumplimientos en situaciones de la rutina de forma natural, lo que se genera cuando hay confianza, se posee madurez del sistema de gestión y un trabajo continuo en el compromiso de las actividades asignadas.` },
    { type: "h", text: `🔸 Auditorias` },
    { type: "p", text: `Muchas veces, las no conformidades sólo aparecen cuando llegan las auditorías, las cuales si bien son una de las herramienta de mejora más importante, son foto de un momento puntual del laboratorio.` },
    { type: "p", text: `Cumplir requisitos está latente continuamente en cada actividad, por ello, anímate, confía y atrévete a mejorar usando los incumplimientos a tu favor.` },
  ],
  "relacion-entre-veracidad-precision-y-exactitud": [
    { type: "p", text: `Por Laura Delissi` },
    { type: "p", text: `Te compartimos este blog para aclarar dudas y definir conceptos, tomando como referencia la guía Eurachem - La Adecuación al Uso de los Métodos Analíticos.` },
    { type: "p", text: `La historia comienza cuando en el laboratorio deseamos describir la calidad de los resultados obtenidos con un método, donde, para que esto suceda, debemos evaluar la veracidad, precisión y exactitud.` },
    { type: "h", text: `1️⃣ Veracidad y errores sistemáticos` },
    { type: "p", text: `Podemos decir que el primer capítulo de esta historia comienza cuando encontramos en un ensayo errores asociados a fallas sistemáticas que generan una variabilidad al valor que realmente debería ser. Es necesario que estos errores sean mínimos dentro del ensayo, y la validación del método es una excelente herramienta para hacer el estudio.` },
    { type: "p", text: `Cuando hablamos de veracidad, podemos decir que es la descripción cualitativa de esas fallas sistemáticas, que llamaremos errores sistemáticos. Si deseamos cuantificar la veracidad y saber que cantidad de errores sistemáticos están presentes en un método de ensayo, lo podemos hacer mediante el cálculo del sesgo, bias o recuperación.` },
    { type: "h", text: `2️⃣ Precisión y errores aleatorios` },
    { type: "p", text: `El segundo capítulo de historia se lo lleva la contracara de los errores sistemáticos, ellos son los errores aleatorios. Estos errores encontrados de forma impredecible en los métodos, se pueden describir cuantitativamente a partir de la precisión, y si deseamos cuantificarlos, para saber el grado de dispersión entre los valores, podemos hacerlo calculando la desviación estándar o coeficiente de variación en diferentes condiciones como pueden ser repetibilidad y precisión intermedia (utilizadas para saber la dispersión de los datos dentro del laboratorio) y reproducibilidad (para saber la dispersión de los datos de un laboratorio con otro).` },
    { type: "h", text: `3️⃣ Exactitud e incertidumbre` },
    { type: "p", text: `Y finalmente, el desenlace de esta historia esta representado por la suma de estos errores. Los errores sistemáticos y aleatorios, forman parte del error total de una medición. Pero... ¿cómo cuantificamos y expresamos este error total? Aquí aparece en escena la exactitud, tomando un total protagonismo sobre el resultado informado. Para expresar cualitativamente los errores totales que presenta un método lo hacemos a partir de la exactitud y si deseamos cuantificar la cantidad de esos errores aleatorios y sistemáticos, o sea, la cantidad de errores totales del método, lo hacemos mediante la incertidumbre.` },
    { type: "p", text: `En fin, podemos ver que un resultado en el laboratorio, posee una mochila de información generada en el proceso analítico, a medida que se fue desarrollando el ensayo. Esta información se traducirá luego en un error total cuantificado a partir de la incertidumbre que acompaña al resultado informado.` },
  ],
  "auditorias-internas-y-cultura-de-calidad": [
    { type: "p", text: `Por Laura Delissi` },
    { type: "p", text: `Muchas veces nos sucede como auditores internos que es complicado encontrar formas de agregar valor en el proceso de auditoría. Para que esto no suceda, podemos analizar al laboratorio a auditar en función de su sistema de gestión y la cultura de calidad presente, representado en 4 zonas.` },
    { type: "h", text: `Zona 1 - Baja madurez de la cultura de calidad y SGC poco conforme con los requisitos` },
    { type: "p", text: `Aquí la cultura de calidad del laboratorio aún no permite desarrollar las actividades con compromiso y fluidez. El personal generalmente no posee conocimientos sobre la importancia de la calidad y la mejora continua. También existe un SGC el cual no se encuentra correctamente desarrollado incumpliendo las normas implementadas.` },
    { type: "p", text: `✔ ¿Cómo aportar valor en estos casos?` },
    { type: "p", text: `Describiendo No Conformidades donde el auditado comprenda que es lo que la norma requiere. Explicar el incumplimiento en detalle para que el laboratorio pueda conocer como a partir del hallazgo se puede disparar la mejora continua.` },
    { type: "h", text: `Zona 2 - Alta madurez de la cultura de calidad y un SGC poco conforme con los requisitos` },
    { type: "p", text: `En este caso el laboratorio necesita saber cómo implementar un SGC y reconocer posibles mejoras en la implementación. Generalmente es una actividad fácil de llevar a cabo ya que la madurez de la cultura de calidad ayuda a que el sistema pueda implementarse con fluidez.` },
    { type: "p", text: `✔ ¿Cómo aportar valor en estos casos?` },
    { type: "p", text: `Entendiendo el modelo de calidad implementado, buscando la forma de mejorarlo, sin insistir en redefinir documentos o procesos para cumplir la norma.` },
    { type: "h", text: `Zona 3 - Baja madurez de la cultura de calidad y un SGC conforme con los requisitos` },
    { type: "p", text: `En estos laboratorios se presenta una característica muy particular, generalmente encontramos una implementación bajo presión o un SGC construido alrededor de los requisitos normativos, lo que resulta en un SGC paralelo, donde lo que está escrito no es lo mismo que se hace en la rutina.` },
    { type: "p", text: `✔ ¿Cómo aportar valor en estos casos?` },
    { type: "p", text: `Aquí el auditor debe incluir en el SGC las actividades diarias, mientras se reconstruye el sistema.` },
    { type: "h", text: `Zona 4 - Alta madurez de la cultura de calidad y un SGC conforme con los requisitos` },
    { type: "p", text: `Esta sin duda es la situación más difícil de auditar, porque todo parece "estar perfecto" y el auditado visualiza a la auditoría como "visitas rutinarias de compromiso". En estos laboratorios vemos al personal involucrado en el SGC, documentos armonizados y que reflejan las actividades, registros completos y todo fluyendo con naturalidad.` },
    { type: "p", text: `✔ ¿Cómo aportar valor en estos casos?` },
    { type: "p", text: `Aquí debemos centrarnos como auditores en debatir con la alta dirección sobre expectativas del SGC y las estrategias para el cumplimiento de objetivos.` },
  ],
  "informacion-documentada-que-mantener-y-conservar": [
    { type: "h", text: `¿Sabés la diferencia entre la información documentada que se debe mantener y la que se debe conservar?` },
    { type: "p", text: `Comencemos en primer lugar por definir a qué llamamos información documentada. Bueno, podríamos buscar definiciones de normas de referencia, pero vamos a desarrollar un concepto más informal, que la define como aquella información que un laboratorio posee para desarrollar sus actividades, por ejemplo procedimientos, instructivos, manuales, formularios, etc. Pero.. ¿cuál de ella se mantiene y cuál se conserva?` },
    { type: "h", text: `🔸 Información documentada a mantener` },
    { type: "p", text: `Existen documentos que deben mantenerse en el laboratorio y esto significa que deben permanecer dentro del sistema de gestión de calidad mientras sean de utilidad.` },
    { type: "h", text: `📌 ¿Qué ventajas posee mantener estos documentos?` },
    { type: "li", text: `Brindan la posibilidad de comunicar información: cuando redactamos un documento del SGC buscamos que el personal que requiera de esa información la conozca, y esta escritura es una forma de comunicarlo.` },
    { type: "li", text: `Genera la conservación del conocimiento: el personal del laboratorio puede rotar, y llevarse consigo la forma de trabajo enseñada y desarrollada en el laboratorio. Para que esto no suceda, y los conocimientos se puedan conservar en el tiempo, el desarrollo de documentos es importante.` },
    { type: "li", text: `Intercambiar conocimientos: a la hora de desarrollar documentos, el personal parte del debate, del consenso y de la experiencia, lo que culmina con un documento sumamente nutritivo y real.` },
    { type: "h", text: `📌 Ejemplos de información documentada que se mantiene` },
    { type: "li", text: `Política de calidad` },
    { type: "li", text: `Alcance del SGC` },
    { type: "li", text: `Objetivos de calidad` },
    { type: "li", text: `Manual de calidad` },
    { type: "li", text: `Organigrama` },
    { type: "li", text: `Procedimientos e instructivos` },
    { type: "li", text: `Documentos externos` },
    { type: "h", text: `🔸 Información documentada a conservar` },
    { type: "p", text: `Llamamos así a toda información que proporciona evidencia objetiva sobre una actividad desarrollada, por eso es la más buscada por los auditores.` },
    { type: "h", text: `📌¿Qué ventajas posee conservar estos documentos?` },
    { type: "li", text: `Demostrar la conformidad con los requisitos del SGC: por ejemplo lo descripto en programas de calibraciones, matrices de riesgo, etc.` },
    { type: "li", text: `Demostrar el rendimiento y la eficacia del SGC: cuando por ejemplo se habla de indicadores u objetivos` },
    { type: "li", text: `Permite tomar decisiones: los datos que contiene este tipo de documentos nos define si una actividad ha sido desarrollada de forma adecuada o si se debe repetir o redefinir` },
    { type: "h", text: `📌Ejemplos de información documentada que se conserva` },
    { type: "li", text: `Registros` },
    { type: "li", text: `Certificados de calibración` },
    { type: "li", text: `Informes de ensayo` },
    { type: "li", text: `Presupuestos` },
    { type: "li", text: `Ordenes de trabajo` },
  ],
  "priorizacion-de-tareas-en-el-laboratorio": [
    { type: "p", text: `Llegás al laboratorio y te espera un día con una rutina agitada y la mente comienza a generar un nivel de ansiedad si no cubrimos todas las actividades. Por eso, en esta nota te compartimos cómo organizar un parte importante de tu trabajo, los correos electrónicos. Llegan mails del tipo:` },
    { type: "li", text: `🔸 importantes, para respuesta inmediata, como reclamos` },
    { type: "li", text: `🔸 de aviso, recordando alguna actividad, como reuniones` },
    { type: "li", text: `🔸 publicitarios, con información útil para el laboratorio, como ser venta de equipos o cursos` },
    { type: "li", text: `🔸 spam, con información que nada tiene que ver con nuestras actividades` },
    { type: "p", text: `El tema es que tu ordenador (y muchas veces tu celular si tienes configurado el mail laboral) suena cada vez que llega un correo electrónico mientras estás realizando otras actividades y aparece un pensamiento... "debo contestar ahora" ... pero no siempre es así y los siguientes tips pueden ayudarte a tranquilizar tu mente y organizar tus tareas:` },
    { type: "li", text: `🔸 estipula momentos en la jornada laboral para revisar tu mail. Puedes, por ejemplo, dependiendo de tu puesto laboral y las actividades que realices en el laboratorio, planificar la revisión de mail tres veces al día:` },
    { type: "li", text: `▪ al comienzo de la jornada: mientras te tomas un buen café o unos mates.` },
    { type: "li", text: `▪ a media jornada: mientras almuerzas, cenas o tienes un break.` },
    { type: "li", text: `▪ al finalizar la jornada: para finalizar tu jornada sin llegar a tu hogar pensando en ello.` },
    { type: "li", text: `🔸 Prioriza los mails: Puedes utilizar el siguiente esquema cada vez que llega un mail para tomar acciones:` },
    { type: "li", text: `1️⃣ Pertinencia: Preguntarte ¿El mail es pertinente? Esto es, si tiene relación con el trabajo, por ejemplo, si es una publicidad de venta matraces, solicitud de aceptación de un documento que sólo tu puedes hacer, o un mail de venta hoteles, que aparece porque hace unos días estuviste organizando un viaje laboral y el algoritmo ahora comienza a compartirte esa información. Si el mail es pertinente toma acciones, en caso contrario, elimínalo rápidamente.` },
    { type: "li", text: `2️⃣ Toma acciones: ¿Lo puedo responder en menos de 2 minutos? si la respuesta es si, hazlo! en caso contrario, tomarás otras acciones.` },
    { type: "li", text: `3️⃣ Otras acciones: Pregúntate ¿Lo respondo luego o lo delego? entonces es momento de organizar:` },
    { type: "li", text: `▪ colocarlo como mail pendiente de respuesta, estipulando hasta cuanto tiempo podes demorar la respuesta.` },
    { type: "li", text: `▪ encontrarle un dueño a la respuesta, esto es delega la responsabilidad a otra persona con la capacidad de responder el mail.` },
    { type: "p", text: `Si bien esta actividad es una pequeña parte en la cantidad de actividades que hacemos día a día en el laboratorio, se lleva mucha carga mental. Organízate y verás como otras actividades comienzan a fluir también.` },
  ],
  "rotulado-de-reactivos-en-el-laboratorio-de-quimica": [
    { type: "p", text: `En el laboratorio preparamos una gran cantidad de reactivos... soluciones estándares, soluciones para reacciones químicas en ensayos, patrones para curvas de calibrado, indicadores para titulaciones, y muchas más. Todas ellas tienen algo en común... Deben llevar una identificación.` },
    { type: "h", text: `¿Qué finalidad posee la identificación de los reactivos?` },
    { type: "p", text: `Generar trazabilidad de la información a partir de:` },
    { type: "li", text: `las iniciales del personal que preparó el reactivo, lo cual es útil si surge algún problema referido a la calificación del personal.` },
    { type: "li", text: `la fecha de preparación, muy útil para saber cuánto hace que el reactivo fue preparado y si aún se encuentra dentro del plazo de vida útil.` },
    { type: "li", text: `la fecha de revalidación o vencimiento, permitirá saber si el reactivo necesita ser actualizado antes de su uso, ya sea por un ensayo de vida útil o mediante un reactivo de reemplazo. Los factores para el descarte o revalidación generalmente se encuentran descriptos en los métodos de referencia.` },
    { type: "li", text: `la concentración de la solución, en ocasiones se preparan varias soluciones idénticas donde solo varia la concentración, por este motivo, es necesario este dato para evitar confusiones a la hora del uso en los ensayos.` },
    { type: "li", text: `las condiciones de almacenamiento, permitirán reconocer rápidamente las formas de almacenar los reactivos para su correcto mantenimiento. En ocasiones esta información puede encontrarse en los métodos de referencia, aunque el proceso de validación del método es una buena instancia para establecer las condiciones de almacenamiento de los reactivos que son críticos para el ensayo.` },
    { type: "li", text: `identificación única, la es recomendable sea correlativa.` },
    { type: "li", text: `cualquier información extra de cuidados, como ser uso de EPP` },
    { type: "h", text: `¿Dónde colocamos toda esta información?` },
    { type: "p", text: `Bueno parece un montón como para colocarla en el frasco donde almacenaremos la solución o droga preparada, pero no te creas! puedes resumirla con iniciales o pictogramas.` },
    { type: "p", text: `En ocasiones el laboratorio puede contar con un sistema de etiquetado automático, el cual imprime las etiquetas con la información que se le indique, pero en otras situaciones, el etiquetado lo hacemos con pegatinas de forma manual a mano alzada. Independientemente de la forma elegida, lo importante es que esté disponible toda la información.` },
    { type: "h", text: `¿Alcanza con la identificación en el frasco?` },
    { type: "p", text: `Lamentablemente la respuesta es no. Debemos generar una conexión entre la información del frasco y los registros del SGC, ya que es ahí donde se genera la verdadera trazabilidad de la información. En estos registros, se suma otra información diferente a la que figura en el frasco y tiene que ver con:` },
    { type: "li", text: `la cantidad de droga utilizada` },
    { type: "li", text: `el lote de la droga utilizada` },
    { type: "li", text: `el diluyente utilizado` },
    { type: "li", text: `cálculos que permitirán la preparación del reactivo` },
  ],
  "correlacion-de-resultados-numeral-7-7-1-iso-17025": [
    { type: "p", text: `Cuando debemos interpretar la norma ISO/IEC 17025 para su aplicación, en ocasiones entramos en duda si lo que entendemos es correcto. Hoy vamos a hablar del numeral 7.7. En este numeral la norma nos comparte una serie (bastante amplia) de posibles actividades para asegurar la validez de los resultados. Si bien no tenemos que aplicar todas las actividades en cada ensayo, alguna debemos escoger. Vamos a centrarnos en el numeral 7.7.1.h "Correlación de resultados para diferentes características de un ítem"` },
    { type: "h", text: `¿Siempre es posible aplicar este numeral?` },
    { type: "p", text: `No siempre este actividad será de aplicabilidad, dependiendo del tipo de muestra.` },
    { type: "h", text: `¿Qué significa la correlatividad de resultados?` },
    { type: "p", text: `Cuando hablamos de correlatividad de resultados nos referimos a que diferentes características de un ítem tienen una relación de concentración que nos permite saber si los resultados obtenidos son criteriosos y correctos. Veamos algunos ejemplos:` },
    { type: "li", text: `Relación de la demanda química de oxígeno (DQO) y la demanda bioquímica de oxígeno (DBO) en muestras de efluentes: la DQO generalmente es mayor que la DBO debido a que la primera mide tanto la cantidad de materia orgánica biodegradable como la no biodegradable.` },
    { type: "li", text: `Relación entre oxidabilidad y demanda bioquímica de oxígeno (DBO) en muestras de efluentes: ambas son medidas de la cantidad de materia orgánica presente en la muestra. Esto se traduce en una relación proporcional donde si la DBO es alta, también lo será la oxidabilidad.` },
    { type: "li", text: `Relación conductividad y sólidos disueltos totales en muestras de agua: en este caso el valor de conductividad es ligeramente mayor que en el sólidos totales, y esto se debe a que el segundo al tener el efecto de la temperatura en el proceso de secado, se produce la volatilización de ciertos minerales que luego no son contemplados en el cálculo, cuestión que no sucede en la medición de conductividad.` },
    { type: "li", text: `Relación entre la concentración de Plata y Oro en muestras de roca: aquí se presenta una correlación que depende del tipo de roca pero existe un porcentaje de ambos minerales ya conocida por los expertos. Lo mismo sucede con la concentración de Calcio y Magnesio en muestras de agua.` },
    { type: "h", text: `Pero hay algo para tener en cuenta...` },
    { type: "p", text: `Para que el analista pueda aplicar estas correlaciones, es importante que haya pasado tiempo realizando los ensayos, es necesario que conozca posibilidades de correlación, que haya estado parado frente a la decisión de tener que aplicar un sentido crítico y analítico, por esto, generalmente esta actividad está bajo la responsabilidad de personal con experiencia en las muestras medidas.` },
  ],
  "no-conformidad-en-mas-de-un-requisito": [
    { type: "p", text: `Hace un tiempo me preguntaron si una misma No Conformidad puede aplicar a diferentes requisitos. En otras palabras, si un incumplimiento puede generar una No Conformidad en más de un requisito.` },
    { type: "h", text: `Vamos a centrarnos en varios ejemplos:` },
    { type: "li", text: `Primera situación: Un laboratorio realiza actividades de formación en el personal pero no se realiza un seguimiento de la competencia. En este caso, el incumplimiento es al numeral 6.2.5.f. de la norma ISO/IEC 17025:2017` },
    { type: "li", text: `Segunda situación: En un laboratorio la fecha de entrega de los ensayos debe ser acordada y declarada con los clientes en el F01- "Contrato". Para un ensayo en particular, se acuerda con el cliente que los resultados serán entregados a los 5 días desde la recepción de la muestra. Existe un inconveniente con los análisis lo que lleva a una demora en la entrega de los resultados pasando los 5 días acordados y el cual no es avisado al cliente. En este caso, el incumplimiento es al numeral 7.1.5 de la norma ISO/IEC 17025:2017 y al F01- "Contratos" como documento interno del SGC del laboratorio.` },
    { type: "li", text: `Tercera situación: Un organismo de acreditación define en sus criterios que cuando un laboratorio acreditado obtiene un resultado insatisfactorio debe darle aviso. Un laboratorio acreditado por este organismo participa en un ensayo de aptitud y obtiene resultados insatisfactorios, pero no reporta la situación ni genera acciones para tratar el resultado internamente. En este caso, el incumplimiento es al numeral 7.7.3 de la norma ISO/IEC 17025:2017 y al documento del OA donde se declara la necesidad de aviso.` },
    { type: "li", text: `Cuarta situación: El laboratorio posee hojas de cálculo en formato digital como registro primario de sus análisis. En dichas hojas no se incluyen la fecha de la actividad y tampoco se encuentran protegidas para que su uso sea seguro. En este caso, el incumplimiento es al numeral 7.5.1 y 8.4.2 de la norma ISO/IEC 17025:2017` },
    { type: "p", text: `En resumen, analizando estas cuatro situaciones, podemos ver que la respuesta a la pregunta es si, puede una situación ser incumplimiento para varios requisitos.` },
  ],
};

export function getBlogContent(slug: string): BlogBlock[] {
  return BLOG_CONTENT[slug] ?? [];
}
